### ISSUE TITLE
Potential Bug in Paper or Code

### ISSUE THREAD

**Issue by chengeharrison** [Ablustrund/LoRAMoE#3]
Hi, thanks for your awesome work.

When I am reading the code plus the paper, I have noticed a potential bug, in the paper, the localized balancing constraint loss is defined as $var^2/mean$.

<img width="110" alt="截屏2024-04-11 下午4 36 40" src="https://github.com/Ablustrund/LoRAMoE/assets/70520919/c8d6dbb8-d267-4029-a3c7-445ed7c3cb37">

However, in the [code](https://github.com/Ablustrund/LoRAMoE/blob/main/peft/tuners/lora.py#L336), the loss is defined as $var/mean^2$. Although this difference doesn't affect the optimization of loss.

Could you please clarify them?

**Comment by Ablustrund** [comment]
Hi, thank you for your valuable comment. 

We use the square of [coefficient of variation](https://en.wikipedia.org/wiki/Coefficient_of_variation) to implement the localized balancing constraint loss. So the loss can be written as $var / mean^2$. We will modify our paper to make it clearer.
