### ISSUE TITLE
transformers版本问题

### ISSUE THREAD

**Issue by lzw-lzw** [Ablustrund/LoRAMoE#7]
你好，我看仓库里写到“In transformers, we mainly change modeling_llama.py to introduce new para task_types.”但requirements.txt里面是有transformers==4.30.2的，那这里应该用你们修改的 transformers 还是 4.30.2 呢，如果在其他项目中用你们修改的transformers，遇到一些 transformers版本太低导致的问题，该如何解决呢。谢谢！

**Comment by lzw-lzw** [comment]
另外我注意到修改的modeling_llama.py中 task_types似乎只在这里forward中有，但forward中task_types也没有用到这个参数，那么引入这个参数是在哪里作用呢，不知道是不是有遗漏的地方。
<img width="662" alt="image" src="https://github.com/Ablustrund/LoRAMoE/assets/66579204/c57be48f-2ced-4d0a-bc76-6dc3b2d37564">

**Comment by Ablustrund** [comment]
您好，这里的llamamlp会被lora中的fnn引用，所以其实相当于lora文件中的fnn中的tasktypes引用这里llamamlp的tasktypes

**Comment by Ablustrund** [comment]
版本过低可以使用更高的版本，然后把llama的改动复制过去，改动没有记错的话只在llama_modeling.py文件

**Comment by lzw-lzw** [comment]
好的，我试试。非常感谢！
